#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port6,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{

motor [port1]=10;
motor [port10]=10;

wait1Msec(2000);

motor [port1]=20;
motor [port10]=20;

wait1Msec(2000);

motor [port1]=30;
motor [port10]=30;
motor [port7]=-10;

wait1Msec(2000);


motor [port1]=40;
motor [port10]=40;

wait1Msec(1000);


motor [port1]=60;
motor [port10]=60;

wait1Msec(1000);


motor [port1]=70;
motor [port10]=70;
motor [port6]=20;

wait1Msec(1000);


motor [port1]=90;
motor [port10]=90;


wait1Msec(1000);


motor [port1]=0;
motor [port10]=0;
motor [port6]=70;
motor [port7]=60;


wait1Msec(2000);
motor [port6]=-70;
wait1Msec(1500);

motor [port7]=-40;
motor[port1]=-100;
motor [port10]=100;


wait1Msec(1275);



motor [port1]=10;
motor [port10]=10;

wait1Msec(2000);

motor [port1]=20;
motor [port10]=20;
motor [port7]=-10;

wait1Msec(2000);

motor [port1]=30;
motor [port10]=30;
motor [port7]=-15;

wait1Msec(2000);


motor [port1]=40;
motor [port10]=40;
motor [port7]=15;

wait1Msec(1000);


motor [port1]=60;
motor [port10]=60;
motor [port7]=-25;

wait1Msec(1000);


motor [port1]=70;
motor [port10]=70;


wait1Msec(1000);


motor [port1]=90;
motor [port10]=90;


wait1Msec(1000);


motor [port1]=0;
motor [port10]=0;

}
