#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{bool a = true;
	int s = 0;
	while(1){
		if (SensorValue[in1]>1800 && SensorValue[in1]>1800){
			s = 1;


					}
		if (SensorValue[in1]>1800 && SensorValue[in1]>1800 &&a == true){
			motor[port1]=0;
			motor[port10]=0;
			wait1Msec(250);
			motor[port1]=50;
			motor[port10]=-50;
			wait1Msec(250);
					}
	motor[port1]=50;
			motor[port10]=-50;
			wait1Msec(10);

}}
