#pragma config(Sensor, dgtl5,  ,               sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


task main()
{
while(1){
	if (SensorValue[dgtl5] < 40){
		motor[port1] = -40;
				motor[port2] = -40;
				motor[port8] = -40;
				motor[port9] = -40;
				wait10Msec(10);
				motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = -40;
				motor[port9] = -40;
				wait1Msec(800);

	}else {
	motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = 40;
				motor[port9] = 40;
				wait10Msec(10);
}
	}


}
