#pragma config(Motor,  port1,            ,             tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor [port1]=5;
motor [port10]=127;

wait1Msec(1000);
motor [port1]=0;
motor [port10]=0;

}
