#pragma config(Motor,  port1,            ,             tmotorVex393TurboSpeed_HBridge, openLoop)
#pragma config(Motor,  port7,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393TurboSpeed_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
motor [port1]=60;
motor [port10]=60;
motor [port7]=-30;

wait1Msec(2000);

motor [port1]=-60;
motor [port10]=-10;
motor [port7]=30;



wait1Msec(3000);
motor [port1]=10;
motor [port10]=110;
motor [port7]=30;

wait1Msec(2000);
motor [port1]=100;
motor [port10]=100;
motor [port7]=-30;

wait1Msec(2500);
motor [port1]=-60;
motor [port10]=60;
motor [port7]=29;

wait1Msec(2000);
motor [port1]=127;
motor [port10]=127;
motor [port7]=30;
motor [port7]=-10;



wait1Msec(4000);
motor [port1]=0;
motor [port10]=0;
motor [port7]=0;





}
