#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port10,           ,             tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while(1)

	{if(SensorValue[in6]>1800)
				{
					motor[port1]=-20;
					motor[port10]=-20;
					wait1Msec(400);
					motor[port1]=50;
					motor[port10]=-50;
					wait1Msec(250);


				}
			else if (SensorValue[in6]>1800 && SensorValue[in7]>1800)
			{
				motor[port1]=-50;
					motor[port10]=-50;
					wait1Msec(1000);
			}
			motor[port1]=30;
			motor[port10]=30;
			wait1Msec(10);
		}




}
