#pragma config(Sensor, in3,    ,               sensorReflection)
#pragma config(Sensor, in4,    ,               sensorReflection)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  ,               sensorSONAR_cm)
#pragma config(Sensor, dgtl7,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl9,  ,               sensorTouch)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
void proezd10cm(){
	bool flag = true;
	SensorValue[dgtl1] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[dgtl7]  = 0;
	while(flag){

		if (SensorValue[dgtl1] < 103 && SensorValue[dgtl7] < 103){
		motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = 35;
				motor[port9] = 35;
				}else{
				motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				flag = false;
				}
	}	motor[port2] = 0;
		motor[port8] = 0;
		motor[port9] = 0;
		motor[port4] = 0;
		wait1Msec(400);}
		void proezddobanki(){
	bool flag = true;
	SensorValue[dgtl1] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[dgtl7]  = 0;
	while(flag){

		if (SensorValue[dgtl5] > 4){
		motor[port1] = 30;
				motor[port2] = 30;
				motor[port8] = 25;
				motor[port9] = 25;
				}else{
				motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				flag = false;
				}
	}	motor[port2] = 0;
		motor[port8] = 0;
		motor[port9] = 0;
		motor[port4] = 0;
		wait1Msec(400);}
void proezd40cm(){
	bool flag = true;
	SensorValue[dgtl1] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[dgtl7]  = 0;
	while(flag){

		if (SensorValue[dgtl1] < 103 && SensorValue[dgtl7] < 103){
		motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = 35;
				motor[port9] = 35;
				}else{
				motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				flag = false;
				}
	}}
void povorot90vlevo(){
	bool flag = true;
	SensorValue[dgtl1] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[dgtl7]  = 0;
	while(flag){

		if (SensorValue[dgtl1] < 240){
		motor[port1] = -40;
				motor[port2] = -40;
				motor[port8] = 35;
				motor[port9] = 35;
				}else{
				motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				flag = false;
				}}
	}
void doezddovpereddo30cm(){
	while(1){
	if (SensorValue[dgtl5] > 30){
		motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = 35;
				motor[port9] = 35;
				motor[port4] = 0;
				wait10Msec(10);
	}else {
	motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				wait10Msec(10);
				break;
}
	}}
	void HVATANIE_S_PROEZDOM(){
		proezddobanki();
		motor[port4] = -60;
		wait1Msec(400);
		proezd10cm();
		motor[port4] = 110;
		wait1Msec(600);
		motor[port4] = 0;
		wait1Msec(100);
	}
task main()

{int c = 0;
	while(1){
	if (SensorValue[dgtl9] == 1 && c == 0){
		c = 1;
		proezd40cm();
		}else if(SensorValue[dgtl9] == 1 && c == 1){
		c = 2;
		povorot90vlevo();
		}else if(SensorValue[dgtl9] == 1 && c == 2){
		c = 3;
		doezddovpereddo30cm();
	}else if(SensorValue[dgtl9] == 1 && c == 3){
		c = 4;
		povorot90vlevo();

}else if(SensorValue[dgtl9] == 1 && c == 4){
		c = 5;
		HVATANIE_S_PROEZDOM();}

}}


//while (c != 0){if (SensorValue[dgtl9] == 0){
//motor[port1] = 50;
		//		motor[port2] = 50;
			//	motor[port8] = 50;
				//motor[port9] = 50;
				//wait1Msec(1000)}}
				//SensorValue[dgtl1] = 0;	  // Set the encoder so that it starts counting at 0
	//SensorValue[dgtl7]  = 0;
//flag = true;
	//while(flag){
	//if (SensorValue[dgtl7]<1000 && SensorValue[dgtl3]<100) {
		//motor[port1] = 60;
			//	motor[port2] = 60;
				//motor[port8] = 45;
				//motor[port9] = 45;
//	}
	//else{
		//motor[port1] = 0;
			//	motor[port2] = 0;
				//motor[port8] = 0;
				//motor[port9] = 0;
				//flag = false;

//}}
//flag = true;
//while(flag){
	//if (SensorValue[dgtl5] > 30){
		//motor[port1] = 40;
				//motor[port2] = 40;
				//motor[port8] = 40;
				//motor[port9] = 40;
				//wait10Msec(10);
	//}else {
	//motor[port1] = 0;
			//	motor[port2] = 0;
				//motor[port8] = 0;
				//motor[port9] = 0;
				//flag = false;
				//wait10Msec(10);
//}
	//}
