#pragma config(Sensor, in3,    ,               sensorReflection)
#pragma config(Sensor, in4,    ,               sensorReflection)
#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  ,               sensorQuadEncoder)
#pragma config(Motor,  port1,            ,             tmotorVex393_HBridge, openLoop, driveLeft)
#pragma config(Motor,  port2,            ,             tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,            ,             tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,            ,             tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port9,            ,             tmotorVex393_MC29, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{bool flag = true;
SensorValue[dgtl1] = 0;	  // Set the encoder so that it starts counting at 0
	SensorValue[dgtl7]  = 0;
flag = true;
	while(flag){
	if (SensorValue[dgtl7]<1000 && SensorValue[dgtl3]<100) {
		motor[port1] = 60;
				motor[port2] = 60;
				motor[port8] = 45;
				motor[port9] = 45;
	}
	else{
		motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				flag = false;

}}
flag = true;
while(flag){
	if (SensorValue[dgtl5] > 30){
		motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = 40;
				motor[port9] = 40;
				wait10Msec(10);
	}else {
	motor[port1] = 0;
				motor[port2] = 0;
				motor[port8] = 0;
				motor[port9] = 0;
				flag = false;
				wait10Msec(10);
}
	}

}
