#pragma config(Sensor, dgtl5,  ,               sensorSONAR_cm)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
while(1){
	if (SensorValue[dgtl5] > 35){
		motor[port1] = 40;
				motor[port2] = 40;
				motor[port8] = 40;
				motor[port9] = 40;
				wait10Msec(10);
	}else {
	motor[port1] = -30;
				motor[port2] = -30;
				motor[port8] = 0;
				motor[port9] = 0;
				wait10Msec(10);
}
	}


}
